### ISSUE TITLE
emby app on samsung tv is not working now

### ISSUE THREAD

**Issue by concordejet** [jellyfin/jellyfin-samsungtv#3]
How can i use this version . Or can it be added to apps on samsung tv as the emby verions will not work with latest jellyfin version 10.2.2.I am willing to test .I use linux but am not a coder.

**Comment by andrewrabert** [comment]
Official Emby apps will not be supported since the Emby team explicitly blocks Jellyfin.

**Comment by concordejet** [comment]
How do i use this version.if i put it in developer mode is there a way to test

**Comment by JustAMan** [comment]
This repo is really outdated, more info here: https://github.com/jellyfin/jellyfin/issues/451

As for running some older Emby app - I don't know if there's a way, plus we don't have this version of older Emby app anywhere (and they didn't release the source).
